config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_active_admin_user!, only: :home

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def index
    @products = Product.all.page(params[:page])
  end
  
  def show
  end  

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def edit
  end

  def update
    @product.update(products_params)
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:name, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!-- <div class="section"> -->
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>
    <div class="main">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_newadd.html.erb
<div class="modalNewProduct">
  <%= simple_form_for [@product], method: :post do |f| %>
    <%= f.input :name %>
    <%= f.association :category %>
    <%= f.submit "Enr", class: "btn btn-success" %>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="form">
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name %>
    <%= f.association :category %>
    <%= f.submit "Enr", class: "btn btn-success" %>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <h1>Produits</h1>
  <%= paginate @products %>
  <div class="row">
    <table>
    <tr>
      <th>Nom</th>
      <th>Categorie</th>
      <th>Fonctions</th>
    </tr>
    <% @products.each do |product| %>
    <tr>
      <td> <p class="card-title"><%= product.name %></p> </td>
      <td> <p class="card-text"><%= product.category.name %></p> </td>
      <td> 
        <%= link_to "", product_path(product), class:"fas fa-eye" %>
        <%= link_to "", edit_product_path(product), class:"fas fa-edit" %>
        <%= link_to "", product_path(product), class:"fas fa-trash",
          method: :delete,
          data: { confirm: "Confirmation ?" } %>
      </td>
    </tr>
    <% end %>
    </table>
    <%= paginate @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="form">
  <h2>Ajout de produit</h2>
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name %>
    <%= f.association :category %>
    <%= f.submit "Enr", class: "btn btn-success" %>
  <% end %>
</div>

app/views/products/show.erb
<div class="card-product">
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p class="card-title"><%= @product.name %></p>
    <p class="card-text"><%= @product.category.name %></p>
    <%= link_to "", products_path, class:"far fa-hand-point-left" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if admin_user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_admin_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <%= link_to "Listes", products_path %>
  <a href="#">Recherche</a>
  <%= link_to "Ajout", new_product_path %>
  <% if admin_user_signed_in? && admin_current_user.admin %>
    <%= link_to "Admin", :root %>
  <% end %>
  <a href="#">About</a>
</div>